# Generated by Django 6.0 on 2025-12-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
