# Generated by Django 6.0 on 2025-12-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_alter_new_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/images'),
        ),
    ]
