# Generated by Django 6.0 on 2025-12-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_time']},
        ),
    ]
